Insert important missing word, and polish wording throughout.
AdaCore/learn pull request #1004
Opened 2024-02-25 20:11 UTC by pat-rogers

2024-02-26 22:41 UTC, gusthoff commented on content/courses/ada-idioms/chapters/constructor_functions_for_abstract_data_types.rst
> +We that definition in place, we can explain how Ada prevents constructor inheritance:
"We" => "With" (I guess...)

2024-02-26 22:43 UTC, gusthoff requested changes
Apart from a small typo, it looks good!

2024-02-27 00:20 UTC, pat-rogers commented
On 26-Feb-24 4:42 PM, Gustavo A. Hoffmann wrote:
> ***@***.**** commented on this pull request.
> 
> ------------------------------------------------------------------------
> 
> In 
> content/courses/ada-idioms/chapters/constructor_functions_for_abstract_data_types.rst <https://github.com/AdaCore/learn/pull/1004#discussion_r1503404037>:
> 
>>  otherwise.
>   
> -When a tagged type is extended, inherited constructor functions automatically
> +We that definition in place, we can explain how Ada prevents constructor inheritance:
> 
> "We" => "With" (I guess...)

Yes indeed, good catch.

Can I ask you to make that change for me please?

2024-03-01 11:37 UTC, gusthoff commented on content/courses/ada-idioms/chapters/constructor_functions_for_abstract_data_types.rst
> +We that definition in place, we can explain how Ada prevents constructor inheritance:
I've just fixed it.

2024-03-01 11:38 UTC, gusthoff approved these changes

2024-03-01 11:39 UTC, merged

2024-03-01 15:25 UTC, pat-rogers commented
> I've just fixed it.

Thanks!