fixed typo in standard library containers.rst
AdaCore/learn pull request #459
Opened 2020-12-08 14:13 UTC by 96RadhikaJadhav

2020-12-08 16:27 UTC, pat-rogers requested changes
Either "specifying" should be deleted, or "using" should be deleted.

2020-12-09 07:28 UTC, 96RadhikaJadhav commented
> Either "specifying" should be deleted, or "using" should be deleted.

@pat-rogers Done. Please review now.

2020-12-09 16:17 UTC, pat-rogers approved these changes

2020-12-09 16:18 UTC, pat-rogers commented
On 09-Dec-20 1:28 AM, Radhika wrote:
>     Either "specifying" should be deleted, or "using" should be deleted.
> 
> @pat-rogers <https://github.com/pat-rogers> Done. Please review now.

Done.

Thanks for finding and correcting these!

2020-12-11 12:39 UTC, merged