Rewrite "array aggregate" sentence, replace `()` with `[]`
AdaCore/learn pull request #710
Opened 2022-04-04 12:37 UTC by reznikmm

2022-04-05 09:25 UTC, yannickmoy requested changes
see typo

2022-04-05 09:25 UTC, yannickmoy commented on content/courses/ada_2022_whats_new/chapters/array_aggregates.rst
> +Another form of iterated component association correspond to a positional
"corresponds"

2022-04-05 16:18 UTC, reznikmm commented on content/courses/ada_2022_whats_new/chapters/array_aggregates.rst
> +Another form of iterated component association correspond to a positional
Fixed and rebased. Thank you

2022-04-08 11:09 UTC, yannickmoy approved these changes

2022-04-08 12:32 UTC, gusthoff commented
Thanks for the review, @yannickmoy!

2022-04-08 12:32 UTC, merged